# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adte(object):
    def setupUi1(self, adte):
        adte.setObjectName("adte")
        adte.setFixedSize(622, 343)
        self.test = QtWidgets.QComboBox(adte)
        self.test.setGeometry(QtCore.QRect(350, 10, 231, 41))
        self.test.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.test.setObjectName("test")
        self.test.addItem("")
        self.test.addItem("")
        self.test.addItem("")
        self.test.addItem("")
        self.label = QtWidgets.QLabel(adte)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 41))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(adte)
        self.line.setGeometry(QtCore.QRect(-30, 50, 721, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(adte)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 191, 21))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.vop = QtWidgets.QLineEdit(adte)
        self.vop.setGeometry(QtCore.QRect(10, 100, 601, 31))
        self.vop.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.vop.setText("")
        self.vop.setObjectName("vop")
        self.line_3 = QtWidgets.QFrame(adte)
        self.line_3.setGeometry(QtCore.QRect(-10, 130, 721, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(adte)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 291, 21))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(adte)
        self.label_5.setGeometry(QtCore.QRect(10, 301, 711, 20))
        self.label_5.setStyleSheet("font: 75 12pt \"System\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(adte)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 711, 20))
        self.label_6.setStyleSheet("font: 75 12pt \"System\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(adte)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 16, 21))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(adte)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 21, 21))
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(adte)
        self.label_9.setGeometry(QtCore.QRect(10, 241, 21, 20))
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(adte)
        self.label_10.setGeometry(QtCore.QRect(10, 270, 21, 21))
        self.label_10.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.otv1 = QtWidgets.QLineEdit(adte)
        self.otv1.setGeometry(QtCore.QRect(30, 180, 271, 21))
        self.otv1.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv1.setText("")
        self.otv1.setObjectName("otv1")
        self.otv2 = QtWidgets.QLineEdit(adte)
        self.otv2.setGeometry(QtCore.QRect(30, 210, 271, 21))
        self.otv2.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv2.setText("")
        self.otv2.setObjectName("otv2")
        self.otv4 = QtWidgets.QLineEdit(adte)
        self.otv4.setGeometry(QtCore.QRect(30, 270, 271, 21))
        self.otv4.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv4.setText("")
        self.otv4.setObjectName("otv4")
        self.otv3 = QtWidgets.QLineEdit(adte)
        self.otv3.setGeometry(QtCore.QRect(30, 240, 271, 21))
        self.otv3.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv3.setText("")
        self.otv3.setObjectName("otv3")
        self.line_5 = QtWidgets.QFrame(adte)
        self.line_5.setGeometry(QtCore.QRect(300, 140, 16, 161))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_11 = QtWidgets.QLabel(adte)
        self.label_11.setGeometry(QtCore.QRect(320, 150, 291, 21))
        self.label_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.otv = QtWidgets.QLineEdit(adte)
        self.otv.setGeometry(QtCore.QRect(320, 180, 291, 31))
        self.otv.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.otv.setText("")
        self.otv.setObjectName("otv")
        self.line_6 = QtWidgets.QFrame(adte)
        self.line_6.setGeometry(QtCore.QRect(310, 210, 721, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(adte)
        self.line_7.setGeometry(QtCore.QRect(0, 290, 721, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.widget = QtWidgets.QWidget(adte)
        self.widget.setGeometry(QtCore.QRect(-800, -330, 1491, 691))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.699182, y2:0.738, stop:0 rgba(0, 0, 0, 237), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.cont = QtWidgets.QPushButton(self.widget)
        self.cont.setGeometry(QtCore.QRect(1180, 560, 231, 41))
        self.cont.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.cont.setObjectName("cont")
        self.err = QtWidgets.QLabel(adte)
        self.err.setGeometry(QtCore.QRect(310, 275, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err.setFont(font)
        self.err.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err.setObjectName("err")
        self.widget.raise_()
        self.test.raise_()
        self.label.raise_()
        self.line.raise_()
        self.label_3.raise_()
        self.vop.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.otv1.raise_()
        self.otv2.raise_()
        self.otv4.raise_()
        self.otv3.raise_()
        self.line_5.raise_()
        self.label_11.raise_()
        self.otv.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.err.raise_()

        self.retranslateUi(adte)
        QtCore.QMetaObject.connectSlotsByName(adte)

    def retranslateUi(self, adte):
        _translate = QtCore.QCoreApplication.translate
        adte.setWindowTitle(_translate("adte", "Form"))
        self.test.setItemText(0, _translate("adte", "Тест на средний уровень"))
        self.test.setItemText(1, _translate("adte", "Placement Test A2/B1"))
        self.test.setItemText(2, _translate("adte", "Placement Test B2/C1"))
        self.test.setItemText(3, _translate("adte", "Placement Test C1/C2"))
        self.label.setText(_translate("adte", "Выберите тест для редактирования"))
        self.label_3.setText(_translate("adte", "Введите ваш вопрос"))
        self.label_4.setText(_translate("adte", "Введите ваши варианты ответов "))
        self.label_5.setText(_translate("adte", "Все действия происходят на ваш страх и риск."))
        self.label_6.setText(_translate("adte", "Прежде чем редактировать тест, прочтите инструкцию в пояснительной записке!"))
        self.label_7.setText(_translate("adte", "1)"))
        self.label_8.setText(_translate("adte", "2)"))
        self.label_9.setText(_translate("adte", "3)"))
        self.label_10.setText(_translate("adte", "4)"))
        self.label_11.setText(_translate("adte", "Введите верный ответ"))
        self.cont.setText(_translate("adte", "Готово"))
        self.err.setText(_translate("adte", "Введите все значения"))
