# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adch(object):
    def setupUi1(self, adch):
        adch.setObjectName("adch")
        adch.setFixedSize(473, 157)
        self.lineEdit = QtWidgets.QLineEdit(adch)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 241, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 2px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(adch)
        self.label.setGeometry(QtCore.QRect(20, 5, 201, 21))
        self.label.setStyleSheet("font: 75 12pt \"System\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(adch)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 391, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"System\";")
        self.label_2.setObjectName("label_2")
        self.err_pas = QtWidgets.QLabel(adch)
        self.err_pas.setGeometry(QtCore.QRect(20, 70, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_pas.setFont(font)
        self.err_pas.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_pas.setObjectName("err_pas")
        self.test = QtWidgets.QComboBox(adch)
        self.test.setGeometry(QtCore.QRect(290, 30, 161, 41))
        self.test.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.test.setObjectName("test")
        self.test.addItem("")
        self.test.addItem("")
        self.label_3 = QtWidgets.QLabel(adch)
        self.label_3.setGeometry(QtCore.QRect(300, 0, 181, 31))
        self.label_3.setStyleSheet("font: 75 12pt \"System\";")
        self.label_3.setObjectName("label_3")
        self.exit = QtWidgets.QPushButton(adch)
        self.exit.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.exit.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.exit.setObjectName("exit")
        self.cont = QtWidgets.QPushButton(adch)
        self.cont.setGeometry(QtCore.QRect(360, 100, 101, 21))
        self.cont.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.cont.setObjectName("cont")
        self.widget = QtWidgets.QWidget(adch)
        self.widget.setGeometry(QtCore.QRect(-600, -440, 1491, 691))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.699182, y2:0.738, stop:0 rgba(0, 0, 0, 237), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.err_pas.raise_()
        self.test.raise_()
        self.label_3.raise_()
        self.exit.raise_()
        self.cont.raise_()

        self.retranslateUi(adch)
        QtCore.QMetaObject.connectSlotsByName(adch)

    def retranslateUi(self, adch):
        _translate = QtCore.QCoreApplication.translate
        adch.setWindowTitle(_translate("adch", "Form"))
        self.lineEdit.setPlaceholderText(_translate("adch", "Password.."))
        self.label.setText(_translate("adch", "Введите пароль доступа"))
        self.label_2.setText(_translate("adch", "Чтобы узнать пароль обратитесь к пояснительной записке "))
        self.err_pas.setText(_translate("adch", "Пароль не верный"))
        self.test.setItemText(0, _translate("adch", "Редактирование"))
        self.test.setItemText(1, _translate("adch", "Добавить вопрос"))
        self.label_3.setText(_translate("adch", "Выберите метод"))
        self.exit.setText(_translate("adch", "Назад"))
        self.cont.setText(_translate("adch", "Войти"))
