# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vxo(object):
    def setupUi(self, vxo):
        vxo.setObjectName("vxo")
        vxo.setFixedSize(400, 300)
        self.label_5 = QtWidgets.QLabel(vxo)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(vxo)
        self.label_4.setGeometry(QtCore.QRect(60, 30, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.back = QtWidgets.QPushButton(vxo)
        self.back.setGeometry(QtCore.QRect(20, 250, 101, 31))
        self.back.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 12pt \"Comic Sans MS\";")
        self.back.setObjectName("back")
        self.cont = QtWidgets.QPushButton(vxo)
        self.cont.setGeometry(QtCore.QRect(280, 250, 101, 31))
        self.cont.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 12pt \"Comic Sans MS\";")
        self.cont.setObjectName("cont")
        self.err_not_found = QtWidgets.QLabel(vxo)
        self.err_not_found.setGeometry(QtCore.QRect(60, 190, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_not_found.setFont(font)
        self.err_not_found.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_not_found.setObjectName("err_not_found")
        self.err_not_found_2 = QtWidgets.QLabel(vxo)
        self.err_not_found_2.setGeometry(QtCore.QRect(60, 190, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_not_found_2.setFont(font)
        self.err_not_found_2.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_not_found_2.setObjectName("err_not_found_2")
        self.widget = QtWidgets.QWidget(vxo)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 801, 551))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(149, 255, 247, 237), stop:0.886364 rgba(201, 107, 255, 255));")
        self.widget.setObjectName("widget")
        self.name_inp = QtWidgets.QLineEdit(self.widget)
        self.name_inp.setGeometry(QtCore.QRect(70, 70, 281, 41))
        self.name_inp.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.name_inp.setObjectName("name_inp")
        self.pas_inp = QtWidgets.QLineEdit(self.widget)
        self.pas_inp.setGeometry(QtCore.QRect(70, 160, 281, 41))
        self.pas_inp.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pas_inp.setObjectName("pas_inp")
        self.widget.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.back.raise_()
        self.cont.raise_()
        self.err_not_found.raise_()
        self.err_not_found_2.raise_()

        self.retranslateUi(vxo)
        QtCore.QMetaObject.connectSlotsByName(vxo)

    def retranslateUi(self, vxo):
        _translate = QtCore.QCoreApplication.translate
        vxo.setWindowTitle(_translate("vxo", "Form"))
        self.label_5.setText(_translate("vxo", "Введите пароль:"))
        self.label_4.setText(_translate("vxo", "Введите ваше имя:"))
        self.back.setText(_translate("vxo", "<-- Назад"))
        self.cont.setText(_translate("vxo", "Готово!"))
        self.err_not_found.setText(_translate("vxo", "Пользователь не найден"))
        self.err_not_found_2.setText(_translate("vxo", "Неверный пароль"))
        self.name_inp.setPlaceholderText(_translate("vxo", "Login.."))
        self.pas_inp.setPlaceholderText(_translate("vxo", "Password.."))
