# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edte(object):
    def setupUi(self, edte):
        edte.setObjectName("edte")
        edte.setFixedSize(625, 405)
        self.test = QtWidgets.QComboBox(edte)
        self.test.setGeometry(QtCore.QRect(350, 10, 231, 41))
        self.test.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.test.setObjectName("test")
        self.test.addItem("")
        self.test.addItem("")
        self.test.addItem("")
        self.test.addItem("")
        self.label = QtWidgets.QLabel(edte)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 41))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(edte)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 191, 41))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.num = QtWidgets.QLineEdit(edte)
        self.num.setGeometry(QtCore.QRect(210, 70, 51, 41))
        self.num.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.num.setText("")
        self.num.setObjectName("num")
        self.line = QtWidgets.QFrame(edte)
        self.line.setGeometry(QtCore.QRect(-30, 50, 721, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(edte)
        self.line_2.setGeometry(QtCore.QRect(-10, 105, 721, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(edte)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.vop = QtWidgets.QLineEdit(edte)
        self.vop.setGeometry(QtCore.QRect(10, 160, 601, 31))
        self.vop.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.vop.setText("")
        self.vop.setObjectName("vop")
        self.line_3 = QtWidgets.QFrame(edte)
        self.line_3.setGeometry(QtCore.QRect(-10, 190, 721, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(edte)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 291, 21))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(edte)
        self.label_5.setGeometry(QtCore.QRect(10, 361, 711, 20))
        self.label_5.setStyleSheet("font: 75 12pt \"System\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(edte)
        self.label_6.setGeometry(QtCore.QRect(10, 380, 711, 20))
        self.label_6.setStyleSheet("font: 75 12pt \"System\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(edte)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 16, 21))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(edte)
        self.label_8.setGeometry(QtCore.QRect(10, 270, 21, 21))
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(edte)
        self.label_9.setGeometry(QtCore.QRect(10, 301, 21, 20))
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(edte)
        self.label_10.setGeometry(QtCore.QRect(10, 330, 21, 21))
        self.label_10.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.otv1 = QtWidgets.QLineEdit(edte)
        self.otv1.setGeometry(QtCore.QRect(30, 240, 271, 21))
        self.otv1.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv1.setText("")
        self.otv1.setObjectName("otv1")
        self.otv2 = QtWidgets.QLineEdit(edte)
        self.otv2.setGeometry(QtCore.QRect(30, 270, 271, 21))
        self.otv2.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv2.setText("")
        self.otv2.setObjectName("otv2")
        self.otv4 = QtWidgets.QLineEdit(edte)
        self.otv4.setGeometry(QtCore.QRect(30, 330, 271, 21))
        self.otv4.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv4.setText("")
        self.otv4.setObjectName("otv4")
        self.otv3 = QtWidgets.QLineEdit(edte)
        self.otv3.setGeometry(QtCore.QRect(30, 300, 271, 21))
        self.otv3.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.otv3.setText("")
        self.otv3.setObjectName("otv3")
        self.line_5 = QtWidgets.QFrame(edte)
        self.line_5.setGeometry(QtCore.QRect(300, 200, 16, 161))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_11 = QtWidgets.QLabel(edte)
        self.label_11.setGeometry(QtCore.QRect(320, 210, 291, 21))
        self.label_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.otv = QtWidgets.QLineEdit(edte)
        self.otv.setGeometry(QtCore.QRect(320, 240, 291, 31))
        self.otv.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.otv.setText("")
        self.otv.setObjectName("otv")
        self.line_6 = QtWidgets.QFrame(edte)
        self.line_6.setGeometry(QtCore.QRect(310, 270, 721, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(edte)
        self.line_7.setGeometry(QtCore.QRect(0, 350, 721, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.widget = QtWidgets.QWidget(edte)
        self.widget.setGeometry(QtCore.QRect(-840, -270, 1491, 691))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.699182, y2:0.738, stop:0 rgba(0, 0, 0, 237), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.cont = QtWidgets.QPushButton(self.widget)
        self.cont.setGeometry(QtCore.QRect(1220, 560, 231, 41))
        self.cont.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border: 1px solid #000000;\n"
"border-radius: 5px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.cont.setObjectName("cont")
        self.err = QtWidgets.QLabel(edte)
        self.err.setGeometry(QtCore.QRect(310, 340, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err.setFont(font)
        self.err.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err.setObjectName("err")
        self.widget.raise_()
        self.test.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.num.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.label_3.raise_()
        self.vop.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.otv1.raise_()
        self.otv2.raise_()
        self.otv4.raise_()
        self.otv3.raise_()
        self.line_5.raise_()
        self.label_11.raise_()
        self.otv.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.err.raise_()

        self.retranslateUi(edte)
        QtCore.QMetaObject.connectSlotsByName(edte)

    def retranslateUi(self, edte):
        _translate = QtCore.QCoreApplication.translate
        edte.setWindowTitle(_translate("edte", "Form"))
        self.test.setItemText(0, _translate("edte", "Тест на средний уровень"))
        self.test.setItemText(1, _translate("edte", "Placement Test A2/B1"))
        self.test.setItemText(2, _translate("edte", "Placement Test B2/C1"))
        self.test.setItemText(3, _translate("edte", "Placement Test C1/C2"))
        self.label.setText(_translate("edte", "Выберите тест для редактирования"))
        self.label_2.setText(_translate("edte", "Введите номер теста"))
        self.label_2.show()
        self.label_3.setText(_translate("edte", "Введите ваш вопрос"))
        self.label_4.setText(_translate("edte", "Введите ваши варианты ответов "))
        self.label_5.setText(_translate("edte", "Все действия происходят на ваш страх и риск."))
        self.label_6.setText(_translate("edte", "Прежде чем редактировать тест, прочтите инструкцию в пояснительной записке!"))
        self.label_7.setText(_translate("edte", "1)"))
        self.label_8.setText(_translate("edte", "2)"))
        self.label_9.setText(_translate("edte", "3)"))
        self.label_10.setText(_translate("edte", "4)"))
        self.label_11.setText(_translate("edte", "Введите верный ответ"))
        self.cont.setText(_translate("edte", "Готово"))
        self.err.setText(_translate("edte", "Введите все значения"))
