# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(803, 558)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_testing = QtWidgets.QPushButton(self.centralwidget)
        self.btn_testing.setEnabled(True)
        self.btn_testing.setGeometry(QtCore.QRect(30, 240, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_testing.setFont(font)
        self.btn_testing.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.btn_testing.setObjectName("btn_testing")
        self.btn_autoriz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_autoriz.setGeometry(QtCore.QRect(280, 340, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_autoriz.setFont(font)
        self.btn_autoriz.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_autoriz.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 25pt \"Comic Sans MS\";")
        self.btn_autoriz.setObjectName("btn_autoriz")
        self.btn_reyt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reyt.setGeometry(QtCore.QRect(480, 430, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_reyt.setFont(font)
        self.btn_reyt.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 26pt \"Comic Sans MS\";")
        self.btn_reyt.setObjectName("btn_reyt")
        self.txt_menu_2 = QtWidgets.QLabel(self.centralwidget)
        self.txt_menu_2.setGeometry(QtCore.QRect(200, 110, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txt_menu_2.setFont(font)
        self.txt_menu_2.setStyleSheet("")
        self.txt_menu_2.setObjectName("txt_menu_2")
        self.txt_menu = QtWidgets.QLabel(self.centralwidget)
        self.txt_menu.setGeometry(QtCore.QRect(0, 0, 601, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txt_menu.setFont(font)
        self.txt_menu.setStyleSheet("")
        self.txt_menu.setObjectName("txt_menu")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 430, 101, 16))
        self.label.setStyleSheet("font: 75 12pt \"System\";")
        self.label.setObjectName("label")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(110, 430, 271, 16))
        self.user.setStyleSheet("font: 75 12pt \"System\";")
        self.user.setText("")
        self.user.setObjectName("user")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-700, -10, 1521, 571))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:0, y2:0, stop:0.227273 rgba(165, 255, 249, 237), stop:0.886364 rgba(210, 131, 255, 255));")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 200, 161, 161))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget.raise_()
        self.btn_autoriz.raise_()
        self.btn_reyt.raise_()
        self.txt_menu_2.raise_()
        self.txt_menu.raise_()
        self.btn_testing.raise_()
        self.label.raise_()
        self.user.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.entrpass = QtWidgets.QAction(MainWindow)
        self.entrpass.setObjectName("entrpass")
        self.menu.addAction(self.entrpass)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_testing.setText(_translate("MainWindow", "Тестирование"))
        self.btn_autoriz.setText(_translate("MainWindow", "Авторизация"))
        self.btn_reyt.setText(_translate("MainWindow", "Общий рейтинг"))
        self.txt_menu_2.setText(_translate("MainWindow", "английского языка!"))
        self.txt_menu.setText(_translate("MainWindow", "  Определите свой уровень"))
        self.label.setText(_translate("MainWindow", "Пользователь:"))
        self.menu.setTitle(_translate("MainWindow", "Админ-меню"))
        self.entrpass.setText(_translate("MainWindow", "Введите пароль"))
