# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getpass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_getpas(object):
    def setupUi(self, getpas):
        getpas.setObjectName("getpas")
        getpas.setFixedSize(411, 372)
        self.label_4 = QtWidgets.QLabel(getpas)
        self.label_4.setGeometry(QtCore.QRect(40, -10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.dater = QtWidgets.QDateEdit(getpas)
        self.dater.setGeometry(QtCore.QRect(40, 150, 131, 31))
        self.dater.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 3px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.dater.setObjectName("dater")
        self.label_6 = QtWidgets.QLabel(getpas)
        self.label_6.setGeometry(QtCore.QRect(40, 110, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(getpas)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.back = QtWidgets.QPushButton(getpas)
        self.back.setGeometry(QtCore.QRect(20, 320, 101, 31))
        self.back.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 12pt \"Comic Sans MS\";")
        self.back.setObjectName("back")
        self.cont_2 = QtWidgets.QPushButton(getpas)
        self.cont_2.setGeometry(QtCore.QRect(250, 160, 121, 41))
        self.cont_2.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.cont_2.setObjectName("cont_2")
        self.widget = QtWidgets.QWidget(getpas)
        self.widget.setGeometry(QtCore.QRect(-30, -20, 801, 551))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(149, 255, 247, 237), stop:0.886364 rgba(201, 107, 255, 255));")
        self.widget.setObjectName("widget")
        self.inp_pass = QtWidgets.QLabel(self.widget)
        self.inp_pass.setGeometry(QtCore.QRect(50, 270, 341, 51))
        self.inp_pass.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.inp_pass.setText("")
        self.inp_pass.setObjectName("inp_pass")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 291, 41))
        self.lineEdit.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.err_name_2 = QtWidgets.QLabel(getpas)
        self.err_name_2.setGeometry(QtCore.QRect(40, 180, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_name_2.setFont(font)
        self.err_name_2.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_name_2.setObjectName("err_name_2")
        self.err_name_3 = QtWidgets.QLabel(getpas)
        self.err_name_3.setGeometry(QtCore.QRect(40, 31, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_name_3.setFont(font)
        self.err_name_3.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_name_3.setObjectName("err_name_3")
        self.widget.raise_()
        self.label_4.raise_()
        self.dater.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.back.raise_()
        self.cont_2.raise_()
        self.err_name_2.raise_()
        self.err_name_3.raise_()

        self.retranslateUi(getpas)
        QtCore.QMetaObject.connectSlotsByName(getpas)

    def retranslateUi(self, getpas):
        _translate = QtCore.QCoreApplication.translate
        getpas.setWindowTitle(_translate("getpas", "Form"))
        self.label_4.setText(_translate("getpas", "Введите ваше имя:"))
        self.label_6.setText(_translate("getpas", "Ваша дата рождения:"))
        self.label_7.setText(_translate("getpas", "Ваш пароль:"))
        self.back.setText(_translate("getpas", "<-- Назад"))
        self.cont_2.setText(_translate("getpas", "Узнать!"))
        self.lineEdit.setPlaceholderText(_translate("getpas", "Login.."))
        self.err_name_2.setText(_translate("getpas", "Дата не верная"))
        self.err_name_3.setText(_translate("getpas", "Имя не найдено"))
