# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg(object):
    def setupUi(self, reg):
        reg.setObjectName("reg")
        reg.setFixedSize(378, 543)
        reg.setStyleSheet("font: 8pt \"Segoe Script\";")
        self.label = QtWidgets.QLabel(reg)
        self.label.setGeometry(QtCore.QRect(20, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label.setObjectName("label")
        self.err_name = QtWidgets.QLabel(reg)
        self.err_name.setGeometry(QtCore.QRect(20, 110, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_name.setFont(font)
        self.err_name.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_name.setObjectName("err_name")
        self.label_2 = QtWidgets.QLabel(reg)
        self.label_2.setGeometry(QtCore.QRect(10, 500, 341, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 12pt \"System\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(reg)
        self.label_3.setGeometry(QtCore.QRect(10, 520, 391, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 12pt \"System\";")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(reg)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(reg)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.cont = QtWidgets.QPushButton(reg)
        self.cont.setGeometry(QtCore.QRect(240, 450, 101, 31))
        self.cont.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 12pt \"Comic Sans MS\";")
        self.cont.setObjectName("cont")
        self.dater = QtWidgets.QDateEdit(reg)
        self.dater.setGeometry(QtCore.QRect(20, 400, 131, 31))
        self.dater.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 3px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.dater.setObjectName("dater")
        self.back = QtWidgets.QPushButton(reg)
        self.back.setGeometry(QtCore.QRect(20, 450, 101, 31))
        self.back.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 12pt \"Comic Sans MS\";")
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(reg)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 18pt \"Segoe Script\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.err_name_2 = QtWidgets.QLabel(reg)
        self.err_name_2.setGeometry(QtCore.QRect(20, 330, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.err_name_2.setFont(font)
        self.err_name_2.setStyleSheet("font: 87 11pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.err_name_2.setObjectName("err_name_2")
        self.widget = QtWidgets.QWidget(reg)
        self.widget.setGeometry(QtCore.QRect(-340, -30, 801, 611))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:0, y2:0, stop:0.227273 rgba(165, 255, 249, 237), stop:0.886364 rgba(210, 131, 255, 255));")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(reg)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 281, 41))
        self.lineEdit.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pas1_inp = QtWidgets.QLineEdit(reg)
        self.pas1_inp.setGeometry(QtCore.QRect(20, 190, 281, 41))
        self.pas1_inp.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pas1_inp.setObjectName("pas1_inp")
        self.pas2_inp = QtWidgets.QLineEdit(reg)
        self.pas2_inp.setGeometry(QtCore.QRect(20, 280, 281, 41))
        self.pas2_inp.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pas2_inp.setObjectName("pas2_inp")
        self.widget.raise_()
        self.label.raise_()
        self.err_name.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.cont.raise_()
        self.dater.raise_()
        self.back.raise_()
        self.label_5.raise_()
        self.err_name_2.raise_()
        self.lineEdit.raise_()
        self.pas1_inp.raise_()
        self.pas2_inp.raise_()

        self.retranslateUi(reg)
        QtCore.QMetaObject.connectSlotsByName(reg)

    def retranslateUi(self, reg):
        _translate = QtCore.QCoreApplication.translate
        reg.setWindowTitle(_translate("reg", "Form"))
        self.label.setText(_translate("reg", "Введите ваше имя:"))
        self.err_name.setText(_translate("reg", "Данное имя уже занято "))
        self.label_2.setText(_translate("reg", "*Все введенные данные в дальнейшем будут "))
        self.label_3.setText(_translate("reg", " использоваться для авторизации и сбора статистики."))
        self.label_6.setText(_translate("reg", "Ваша дата рождения:"))
        self.label_4.setText(_translate("reg", "Введите ваш пароль:"))
        self.cont.setText(_translate("reg", "Готово!"))
        self.back.setText(_translate("reg", "<-- Назад"))
        self.label_5.setText(_translate("reg", "И ещё раз:"))
        self.err_name_2.setText(_translate("reg", "Пароли не совпадают"))
        self.lineEdit.setPlaceholderText(_translate("reg", "Login.."))
        self.pas1_inp.setPlaceholderText(_translate("reg", "Password.."))
        self.pas2_inp.setPlaceholderText(_translate("reg", "Password.."))
