# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tests.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tests(object):
    def setupUi(self, tests):
        tests.setObjectName("tests")
        tests.setFixedSize(800, 600)
        tests.setStyleSheet("")
        self.btn_ts_a = QtWidgets.QPushButton(tests)
        self.btn_ts_a.setEnabled(True)
        self.btn_ts_a.setGeometry(QtCore.QRect(30, 140, 741, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_ts_a.setFont(font)
        self.btn_ts_a.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.btn_ts_a.setObjectName("btn_ts_a")
        self.btn_ts_b = QtWidgets.QPushButton(tests)
        self.btn_ts_b.setEnabled(True)
        self.btn_ts_b.setGeometry(QtCore.QRect(30, 250, 741, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_ts_b.setFont(font)
        self.btn_ts_b.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.btn_ts_b.setObjectName("btn_ts_b")
        self.btn_ts_c = QtWidgets.QPushButton(tests)
        self.btn_ts_c.setEnabled(True)
        self.btn_ts_c.setGeometry(QtCore.QRect(30, 360, 741, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_ts_c.setFont(font)
        self.btn_ts_c.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.btn_ts_c.setObjectName("btn_ts_c")
        self.btn_ts = QtWidgets.QPushButton(tests)
        self.btn_ts.setEnabled(True)
        self.btn_ts.setGeometry(QtCore.QRect(30, 20, 741, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_ts.setFont(font)
        self.btn_ts.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 28pt \"Comic Sans MS\";\n"
"")
        self.btn_ts.setObjectName("btn_ts")
        self.widget = QtWidgets.QWidget(tests)
        self.widget.setGeometry(QtCore.QRect(-300, -200, 1531, 881))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.btn_ex = QtWidgets.QPushButton(tests)
        self.btn_ex.setEnabled(True)
        self.btn_ex.setGeometry(QtCore.QRect(510, 520, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_ex.setFont(font)
        self.btn_ex.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 25pt \"Comic Sans MS\";")
        self.btn_ex.setObjectName("btn_ex")
        self.widget_2 = QtWidgets.QWidget(tests)
        self.widget_2.setGeometry(QtCore.QRect(-20, -10, 901, 671))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(149, 255, 247, 237), stop:0.886364 rgba(201, 107, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.raise_()
        self.widget.raise_()
        self.btn_ts_a.raise_()
        self.btn_ts_b.raise_()
        self.btn_ts_c.raise_()
        self.btn_ts.raise_()
        self.btn_ex.raise_()

        self.retranslateUi(tests)
        QtCore.QMetaObject.connectSlotsByName(tests)

    def retranslateUi(self, tests):
        _translate = QtCore.QCoreApplication.translate
        tests.setWindowTitle(_translate("tests", "Dialog"))
        self.btn_ts_a.setText(_translate("tests", "Placement Test A2/B1"))
        self.btn_ts_b.setText(_translate("tests", "Placement Test B2/C1"))
        self.btn_ts_c.setText(_translate("tests", "Placement Test C1/C2"))
        self.btn_ts.setText(_translate("tests", "Узнать средний уровень "))
        self.btn_ex.setText(_translate("tests", "<-- Назад"))
