# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formtes(object):
    def setupUi(self, formtes):
        formtes.setObjectName("formtes")
        formtes.setFixedSize(1167, 331)
        self.otv = QtWidgets.QComboBox(formtes)
        self.otv.setGeometry(QtCore.QRect(250, 270, 61, 41))
        self.otv.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 5px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.otv.setObjectName("otv")
        self.otv.addItem("")
        self.otv.addItem("")
        self.otv.addItem("")
        self.otv.addItem("")
        self.task = QtWidgets.QLabel(formtes)
        self.task.setGeometry(QtCore.QRect(60, 110, 1111, 71))
        self.task.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(152, 29, 29);")
        self.task.setObjectName("task")
        self.label_2 = QtWidgets.QLabel(formtes)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 1021, 51))
        self.label_2.setStyleSheet("font: 75 25pt \"Segoe Print\";")
        self.label_2.setObjectName("label_2")
        self.anc_1 = QtWidgets.QLabel(formtes)
        self.anc_1.setGeometry(QtCore.QRect(40, 210, 251, 31))
        self.anc_1.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.anc_1.setObjectName("anc_1")
        self.anc_2 = QtWidgets.QLabel(formtes)
        self.anc_2.setGeometry(QtCore.QRect(330, 210, 251, 31))
        self.anc_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.anc_2.setObjectName("anc_2")
        self.anc_3 = QtWidgets.QLabel(formtes)
        self.anc_3.setGeometry(QtCore.QRect(620, 210, 251, 31))
        self.anc_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.anc_3.setObjectName("anc_3")
        self.anc_4 = QtWidgets.QLabel(formtes)
        self.anc_4.setGeometry(QtCore.QRect(910, 210, 241, 31))
        self.anc_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.anc_4.setObjectName("anc_4")
        self.a = QtWidgets.QLabel(formtes)
        self.a.setGeometry(QtCore.QRect(10, 210, 21, 31))
        self.a.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.a.setObjectName("a")
        self.b = QtWidgets.QLabel(formtes)
        self.b.setGeometry(QtCore.QRect(300, 210, 21, 31))
        self.b.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.b.setObjectName("b")
        self.c = QtWidgets.QLabel(formtes)
        self.c.setGeometry(QtCore.QRect(590, 210, 21, 31))
        self.c.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.c.setObjectName("c")
        self.d = QtWidgets.QLabel(formtes)
        self.d.setGeometry(QtCore.QRect(880, 210, 21, 31))
        self.d.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.d.setObjectName("d")
        self.label_11 = QtWidgets.QLabel(formtes)
        self.label_11.setGeometry(QtCore.QRect(20, 280, 221, 21))
        self.label_11.setStyleSheet("font: 75 15pt \"Comic Sans MS\";")
        self.label_11.setObjectName("label_11")
        self.chet = QtWidgets.QLabel(formtes)
        self.chet.setGeometry(QtCore.QRect(10, 130, 41, 31))
        self.chet.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.chet.setObjectName("chet")
        self.chet_2 = QtWidgets.QLabel(formtes)
        self.chet_2.setGeometry(QtCore.QRect(46, 130, 20, 31))
        self.chet_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.chet_2.setObjectName("chet_2")
        self.label_12 = QtWidgets.QLabel(formtes)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.label_12.setStyleSheet("font: 75 12pt \"Segoe Print\";")
        self.label_12.setObjectName("label_12")
        self.chet_3 = QtWidgets.QLabel(formtes)
        self.chet_3.setGeometry(QtCore.QRect(250, 20, 41, 31))
        self.chet_3.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(173, 0, 0);")
        self.chet_3.setObjectName("chet_3")
        self.prog = QtWidgets.QProgressBar(formtes)
        self.prog.setGeometry(QtCore.QRect(0, 0, 1171, 16))
        self.prog.setStyleSheet("text-align: center;\n"
"border-radius: 6px;\n"
"background-color: rgb(172, 255, 172);")
        self.prog.setProperty("value", 24)
        self.prog.setObjectName("prog")
        self.con = QtWidgets.QPushButton(formtes)
        self.con.setGeometry(QtCore.QRect(440, 270, 711, 41))
        self.con.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 16pt \"Comic Sans MS\";")
        self.con.setObjectName("con")
        self.label = QtWidgets.QLabel(formtes)
        self.label.setGeometry(QtCore.QRect(1050, 50, 111, 31))
        self.label.setStyleSheet("font: 75 18pt \"Comic Sans MS\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(formtes)
        self.label_3.setGeometry(QtCore.QRect(1070, 30, 71, 21))
        self.label_3.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(formtes)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1621, 551))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(149, 255, 247, 237), stop:0.886364 rgba(201, 107, 255, 255));")
        self.widget.setObjectName("widget")
        self.cont = QtWidgets.QPushButton(formtes)
        self.cont.setGeometry(QtCore.QRect(440, 270, 711, 41))
        self.cont.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.cont.setObjectName("cont")
        self.lineEdit = QtWidgets.QLineEdit(formtes)
        self.lineEdit.setGeometry(QtCore.QRect(10, 190, 1061, 61))
        self.lineEdit.setStyleSheet("background-color:#d8fffb;\n"
"border: 2px solid #ff7474;\n"
"border-radius: 10px;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.otv_2 = QtWidgets.QComboBox(formtes)
        self.otv_2.setGeometry(QtCore.QRect(250, 270, 61, 41))
        self.otv_2.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.227273 rgba(255, 203, 81, 237), stop:0.886364 rgba(255, 134, 73, 255));\n"
"border: 2px solid #ff7474;\n"
"border-radius: 5px;\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.otv_2.setObjectName("otv_2")
        self.otv_2.addItem("")
        self.otv_2.addItem("")
        self.otv_2.addItem("")
        self.widget.raise_()
        self.lineEdit.raise_()
        self.otv.raise_()
        self.task.raise_()
        self.label_2.raise_()
        self.anc_1.raise_()
        self.anc_2.raise_()
        self.anc_3.raise_()
        self.anc_4.raise_()
        self.a.raise_()
        self.b.raise_()
        self.c.raise_()
        self.d.raise_()
        self.label_11.raise_()
        self.chet.raise_()
        self.chet_2.raise_()
        self.label_12.raise_()
        self.chet_3.raise_()
        self.prog.raise_()
        self.con.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.cont.raise_()
        self.otv_2.raise_()

        self.retranslateUi(formtes)
        QtCore.QMetaObject.connectSlotsByName(formtes)

    def retranslateUi(self, formtes):
        _translate = QtCore.QCoreApplication.translate
        formtes.setWindowTitle(_translate("formtes", "Form"))
        self.otv.setItemText(0, _translate("formtes", "A"))
        self.otv.setItemText(1, _translate("formtes", "B"))
        self.otv.setItemText(2, _translate("formtes", "C"))
        self.otv.setItemText(3, _translate("formtes", "D"))
        self.task.setText(_translate("formtes", "-"))
        self.label_2.setText(_translate("formtes", "Ответье на ряд вопросов для определения вашего уровня"))
        self.anc_1.setText(_translate("formtes", "-"))
        self.anc_2.setText(_translate("formtes", "-"))
        self.anc_3.setText(_translate("formtes", "-"))
        self.anc_4.setText(_translate("formtes", "-"))
        self.a.setText(_translate("formtes", "A"))
        self.b.setText(_translate("formtes", "B"))
        self.c.setText(_translate("formtes", "C"))
        self.d.setText(_translate("formtes", "D"))
        self.label_11.setText(_translate("formtes", "Выберите ваш вариант:"))
        self.chet.setText(_translate("formtes", "-"))
        self.chet_2.setText(_translate("formtes", "-"))
        self.label_12.setText(_translate("formtes", "Текущее количество баллов:"))
        self.chet_3.setText(_translate("formtes", "-"))
        self.con.setText(_translate("formtes", "Готово!"))
        self.label_3.setText(_translate("formtes", "Время:"))
        self.cont.setText(_translate("formtes", "Далее"))
        self.otv_2.setItemText(0, _translate("formtes", "A"))
        self.otv_2.setItemText(1, _translate("formtes", "B"))
        self.otv_2.setItemText(2, _translate("formtes", "C"))
